version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly'
          day: 'monday'
          time: '18:00'
          timezone: 'Europe/Warsaw'
      versioning-strategy: 'increase'
      groups:
        production-dependencies:
          dependency-type: "production"
        development-dependencies:
          dependency-type: "development"
