# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Comandeer's blog
lang: pl
email: comandeer@comandeer.pl
description: > # this means to ignore newlines until "baseurl:"
  Kolejny nudny blog kolejnego nudnego fanatyka JS-a. Nie czytać, nie warto tracić czasu.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://comandeer.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Comandeer
google_analytics: UA-33158520-3
disqus:
  shortname: comandeers-blog
feed:
  path: "feeds/feed.xml"
categories_names:
  'na-luzie': "Na luzie"
  'javascript': "Javascript"
  'a11y': "Dostępność"
  'html-css': "HTML i CSS"
  'daj-sie-poznac-2017': "Daj się poznać 2017"

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
